-- MySQL Script generated by MySQL Workbench
-- Mon Jul  6 19:58:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_ConectaWork
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_ConectaWork
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_ConectaWork` DEFAULT CHARACTER SET utf8 ;
USE `BD_ConectaWork` ;

-- -----------------------------------------------------
-- Table `BD_ConectaWork`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ConectaWork`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ConectaWork`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ConectaWork`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `activo` TINYINT NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) ,
  INDEX `fk_usuario_rol_idx` (`id_rol` ASC) ,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `BD_ConectaWork`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ConectaWork`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ConectaWork`.`area` (
  `id_area` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_area`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ConectaWork`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ConectaWork`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_area` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `correo_empresarial` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `modalidad_trabajo` ENUM('Presencial', 'Remoto', 'Hibrido') NOT NULL,
  PRIMARY KEY (`id_empleado`),
  UNIQUE INDEX `correo_empresarial_UNIQUE` (`correo_empresarial` ASC) ,
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC) ,
  INDEX `fk_empleado_area_idx` (`id_area` ASC) ,
  INDEX `fk_empleado_usuario_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_empleado_area`
    FOREIGN KEY (`id_area`)
    REFERENCES `BD_ConectaWork`.`area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `BD_ConectaWork`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ConectaWork`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ConectaWork`.`tarea` (
  `id_tarea` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `estado` VARCHAR(20) NOT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_tarea`),
  INDEX `fk_tarea_empleado_idx` (`id_empleado` ASC) ,
  CONSTRAINT `fk_tarea_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `BD_ConectaWork`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ConectaWork`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ConectaWork`.`permiso` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  `motivo` TEXT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_permiso`),
  INDEX `fk_permiso_empleado_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_permiso_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `BD_ConectaWork`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ConectaWork`.`incapacidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ConectaWork`.`incapacidad` (
  `id_incapacidad` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `diagnostico` TEXT NULL,
  `soporte` VARCHAR(255) NULL,
  `estado` VARCHAR(20) NOT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_incapacidad`),
  INDEX `fk_incapacidad_empleado_idx` (`id_empleado` ASC) ,
  CONSTRAINT `fk_incapacidad_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `BD_ConectaWork`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ConectaWork`.`novedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ConectaWork`.`novedad` (
  `id_novedad` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_publicacion` DATE NOT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_novedad`),
  INDEX `fk_novedad_empleado_idx` (`id_empleado` ASC) ,
  CONSTRAINT `fk_novedad_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `BD_ConectaWork`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ConectaWork`.`capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ConectaWork`.`capacitacion` (
  `id_capacitacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL,
  `fecha` DATE NOT NULL,
  `duracion_horas` INT NOT NULL,
  PRIMARY KEY (`id_capacitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ConectaWork`.`empleado_capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ConectaWork`.`empleado_capacitacion` (
  `id_empleado` INT NOT NULL,
  `id_capacitacion` INT NOT NULL,
  `fecha_realizacion` DATE NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_empleado`, `id_capacitacion`),
  INDEX `fk_empcap_capacitacion_idx` (`id_capacitacion` ASC) ,
  CONSTRAINT `fk_empcap_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `BD_ConectaWork`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empcap_capacitacion`
    FOREIGN KEY (`id_capacitacion`)
    REFERENCES `BD_ConectaWork`.`capacitacion` (`id_capacitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
